apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  labels:
    app: django-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: registry.digitalocean.com/cr-k8s/django-k8s-web:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: django-web-env-prod
        env:
          - name: PORT
            value: "3000"
        ports:
        - containerPort: 3000
        imagePullSecrets:
        - name: cr-k8s 


---
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: django-k8s-web-deployment